import {useEffect,useMemo,useState} from "react";
import {Waves,GitBranch,Plus,History,LayoutDashboard,ShieldAlert,Layers,Boxes,Bug,Network,ScanSearch,BookOpen,Info,X,ArrowRight,ExternalLink,Menu,Search,Radio} from "lucide-react";
import {Button} from "./ui/Button";
import {DependencyGraph} from "./DependencyGraph";
import {PackageDetails} from "./PackageDetails";
import {OtterDrawer,type Focus} from "./OtterDrawer";
import {scanFacts,severity,versionLabel,sections,type Section,type Finding} from "../../shared/workspace";
import type {Scan,Simulation,PackageNode} from "../../shared/types";
import type {OtterAction} from "../../server/otter";
const icons=[LayoutDashboard,ShieldAlert,Layers,Boxes,Bug,Network,ScanSearch,BookOpen];
const slug=(s:Section)=>s.toLowerCase().replaceAll(" ","-");
function initialSection(){return sections.find(s=>slug(s)===location.hash.slice(1))||"Overview";}
export function Workspace({scan,api,onNew,onHistory,onExport}:{scan:Scan;api:<T>(path:string,body?:unknown)=>Promise<T>;onNew:()=>void;onHistory:()=>void;onExport:()=>void}){
 const facts=useMemo(()=>scanFacts(scan),[scan]);
 const [section,setSection]=useState<Section>(initialSection);
 const [application,setApplication]=useState("");
 const [selected,setSelected]=useState(scan.risks?.[0]?.nodeId||facts.packages[0]?.id||"");
 const [query,setQuery]=useState("");const [filter,setFilter]=useState("all");
 const [brief,setBrief]=useState<Finding|null>(null);
 const [otter,setOtter]=useState(false);const [focus,setFocus]=useState<Focus|null>(null);
 const [paths,setPaths]=useState<Simulation|null>(null);const [ripple,setRipple]=useState(false);const [error,setError]=useState("");
 const [menu,setMenu]=useState(false);
 const node=scan.graph!.nodes.find(n=>n.id===selected);
 const risk=scan.risks?.find(r=>r.nodeId===selected)||scan.risks?.find(r=>scan.graph!.nodes.find(n=>n.id===r.nodeId)?.purl===node?.purl);
 const scopedPackages=application?facts.packages.filter(n=>facts.appsFor(n).includes(application)):facts.packages;
 const scopedFindings=application?facts.findings.filter(f=>f.applications.includes(application)):facts.findings;
 const selectedApplication=facts.roots.find(n=>n.id===application);
 const nav=(next:Section)=>{setSection(next);setQuery("");setFilter("all");setMenu(false);window.history.replaceState(null,"","/app#"+slug(next));};
 function select(id:string,target:Section="Dependencies"){setSelected(id);nav(target);}
 function follow(action:OtterAction){if(action.nodeId)setSelected(action.nodeId);if(action.applicationId!==undefined)setApplication(action.applicationId);nav(action.section);}
 useEffect(()=>{setPaths(null);setRipple(false);setError("");if(!selected)return;let active=true;api<Simulation>("/scans/"+scan.id+"/simulate",{nodeId:selected}).then(p=>{if(active)setPaths(p);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[selected,scan.id]);
 useEffect(()=>{const f=()=>setSection(initialSection());window.addEventListener("hashchange",f);return()=>window.removeEventListener("hashchange",f);},[]);
 const exact=scopedPackages.filter(n=>n.versionStatus!=="unresolved");
 const checked=exact.filter(n=>n.coverage==="checked"||n.coverage==="fixture").length;
 const unresolved=scopedPackages.length-exact.length;
 const priorities=(scan.risks||[]).filter(r=>r.advisories>0&&scopedPackages.some(n=>n.id===r.nodeId||n.purl===scan.graph!.nodes.find(x=>x.id===r.nodeId)?.purl));
 const uniqueAdvisories=new Map(scopedFindings.map(f=>[f.advisory.id,f.advisory]));
 const severityCounts=["critical","high","medium","low","unknown"].map(s=>({label:s,count:[...uniqueAdvisories.values()].filter(a=>severity(a)===s).length}));
 const exposure=[{label:"Direct",count:scopedFindings.filter(f=>f.node.depth===1).length},{label:"Indirect",count:scopedFindings.filter(f=>(f.node.depth||0)>1).length},{label:"Unknown",count:scopedFindings.filter(f=>f.node.depth===null).length}];
 const matches=(n:PackageNode)=>n.name.toLowerCase().includes(query.toLowerCase())&&(filter==="all"||filter===n.ecosystem||filter===n.scope||filter==="vulnerable"&&n.advisories.length>0||filter==="unresolved"&&n.versionStatus==="unresolved"||filter==="direct"&&n.depth===1||filter==="indirect"&&(n.depth||0)>1||filter==="exploited"&&n.advisories.some(a=>a.exploited)||["critical","high"].includes(filter)&&n.advisories.some(a=>severity(a)===filter));
 const describeDepth=(n:PackageNode)=>n.depth===null?"Depth unavailable":n.depth===1?"Direct":"Hidden "+n.depth+" levels deep";
 const appNames=(ids:string[])=>ids.map(id=>facts.roots.find(r=>r.id===id)?.name).filter(Boolean).join(", ");
 const filterBar=(type:"risk"|"inventory"|"vulnerability")=><div className="workspace-filters"><label><Search size={16}/><input aria-label={type==="inventory"?"Search dependencies":type==="risk"?"Search risks":"Search vulnerabilities"} placeholder={type==="vulnerability"?"Search advisory or package…":"Search packages…"} value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Filter findings" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All</option>{(type==="risk"?["critical","high","exploited","runtime","indirect"]:type==="inventory"?["direct","indirect","runtime","development","vulnerable","unresolved","npm","pypi","maven"]:["critical","high","exploited","runtime","indirect"]).map(f=><option key={f} value={f}>{f==="pypi"?"Python":f==="exploited"?"Known exploited":f[0].toUpperCase()+f.slice(1)}</option>)}</select></div>;
 const openBrief=(finding:Finding)=>{setBrief(finding);setSelected(finding.node.id);};
 const renderBrief=(finding:Finding)=><section className="vulnerability-brief" aria-label="Vulnerability Brief"><div className="brief-heading"><div><h2>Vulnerability Brief</h2><p>{finding.advisory.id} · {finding.node.name}@{finding.node.version}</p></div><Button aria-label="Close vulnerability brief" onClick={()=>setBrief(null)}><X size={18}/></Button></div><p className="brief-summary">{finding.advisory.summary}</p><dl className="fact-grid"><div><dt>Severity</dt><dd>{severity(finding.advisory)} · CVSS {finding.advisory.cvss??"not supplied"}</dd></div><div><dt>Known exploitation</dt><dd>{finding.advisory.exploited?"Reported by a source":"No evidence in this snapshot"}</dd></div><div><dt>In this repository</dt><dd>{describeDepth(finding.node)} · {finding.node.scope}</dd></div><div><dt>Affected applications</dt><dd>{appNames(finding.applications)||"No recorded path"}</dd></div><div><dt>Fixed version evidence</dt><dd>{finding.advisory.fixed||"No verified fixed version supplied"}</dd></div></dl>{paths?.nodeId===finding.node.id&&<div className="brief-paths">{paths.paths.slice(0,3).map((p,i)=><p key={i}>{p.map(id=>scan.graph!.nodes.find(n=>n.id===id)?.name).join(" → ")}</p>)}<small>Recorded dependency paths; code execution is not established.</small></div>}<div className="evidence-links">{finding.advisory.provenance.map((p,i)=><span key={i}>{p.url.startsWith("https://")?<a href={p.url} target="_blank" rel="noreferrer">{p.source}<ExternalLink size={12}/></a>:p.source}<small>{new Date(p.retrievedAt).toLocaleString()}</small></span>)}</div><div className="brief-actions"><Button className="primary" onClick={()=>{setFocus({nodeId:finding.node.id,advisoryId:finding.advisory.id});setOtter(true);}}>Ask OTTER about this vulnerability</Button><Button onClick={()=>select(finding.node.id,"Ripple Graph")}>Open dependency path</Button></div></section>;
 return <div className={"rootline-workspace journey-app "+(otter?"with-otter":"")}>
  <aside className={"workspace-nav "+(menu?"open":"")}><a className="brand" href="/"><Radio size={23}/>RootLine</a><p className="nav-repo">{scan.name}</p><nav aria-label="Workspace sections">{sections.map((s,i)=>{const Icon=icons[i];return <button key={s} aria-current={section===s?"page":undefined} onClick={()=>nav(s)}><Icon size={18}/>{s}</button>;})}<div className="nav-divider"/><button onClick={onNew}><Plus size={18}/>New Scan</button><button onClick={onHistory}><History size={18}/>Scan History</button></nav><button className="otter-launch" onClick={()=>setOtter(true)}><Waves size={20}/><span>OTTER<small>Explain this investigation</small></span></button><small className="nav-foot">Evidence before assumptions.</small></aside>
  <div className="workspace-main">
   <header className="repository-context"><button className="mobile-nav-button" aria-label="Toggle navigation" onClick={()=>setMenu(!menu)}><Menu size={21}/></button><GitBranch size={17}/><div><strong>{scan.name}</strong><span>{scan.ref} · <code title={scan.commit}>{scan.commit?.slice(0,12)}</code></span></div><span className={"snapshot-state "+(scan.mode==="demo"?"demo":"")}>{scan.mode==="demo"?"Synthetic demo":"Analysis complete"}</span><Button className="otter-top-button" onClick={()=>setOtter(true)}><Waves size={16}/>OTTER</Button></header>
   <main className="workspace-content">
    <div className="section-heading"><div><h1>{section}</h1><p>{({Overview:"Understand the scan. Choose where to look next.",Risks:"Investigate the dependencies that deserve attention first.",Applications:"Compare exposure across the projects you selected.",Dependencies:"Explore exact versions and unresolved declarations.",Vulnerabilities:"Inspect each known finding and the evidence behind it.","Ripple Graph":"Find why a dependency is here. Follow where its impact spreads.",Coverage:"See what was checked, what is partial, and what is unknown.",Evidence:"Verify the sources behind each security statement."})[section]}</p></div><label className="application-scope">Application<select aria-label="Application context" value={application} onChange={e=>setApplication(e.target.value)}><option value="">All applications</option>{facts.roots.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label></div>
    {scan.mode==="demo"&&<p className="workspace-notice">Synthetic demo findings and illustrative dependency paths. No external security source was queried.</p>}
    {error&&<p role="alert" className="workspace-notice">{error}</p>}
    {section==="Overview"&&<>
     <div className="overview-metrics">{[[application?1:facts.roots.length,"Applications"],[scopedPackages.length,"Dependencies discovered"],[uniqueAdvisories.size,"Known advisory IDs"],[priorities.filter(r=>r.score>=60).length,"High-priority dependencies"],[checked+"/"+exact.length,"Exact versions checked"]].map(([value,label])=><div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div>
     <div className="overview-charts">
      <Chart title="How severe are the findings?" subtitle="Distinct advisory IDs by source severity." rows={severityCounts} onClick={()=>nav("Vulnerabilities")}/>
      <Chart title="Which application needs attention?" subtitle="Distinct advisory IDs connected through recorded dependencies." rows={facts.applications.filter(a=>!application||a.root.id===application).map(a=>({label:a.root.name,count:new Set(a.findings.map(f=>f.advisory.id)).size}))} onClick={()=>nav("Applications")}/>
      <Chart title="How much risk is hidden?" subtitle="Package–advisory findings by dependency depth." rows={exposure} onClick={()=>nav("Dependencies")}/>
      <Chart title="How complete is this scan?" subtitle="Dependency versions and unresolved declarations." rows={[{label:"Checked exact",count:checked},{label:"Unchecked exact",count:exact.length-checked},{label:"Unresolved",count:unresolved}]} onClick={()=>nav("Coverage")}/>
     </div>
     <section className="attention-list"><h2>Top things requiring attention</h2>{priorities.slice(0,3).map(r=>{const n=scan.graph!.nodes.find(n=>n.id===r.nodeId)!;return <button key={r.nodeId} onClick={()=>select(r.nodeId,"Risks")}><span className={"priority-mark "+r.level}>{r.score}</span><span><strong>{n.name} <small>{n.version}</small></strong><p>{r.reasons?.slice(0,3).join(" · ")}</p></span><ArrowRight size={18}/></button>;})}{!priorities.length&&<p>{unresolved?"Dependencies were discovered, but some exact installed versions are unavailable. Review coverage before drawing a conclusion.":"No known vulnerabilities were found in packages successfully checked. This is not a claim that the repository is secure."}</p>}<Button onClick={()=>nav("Risks")}>View all risks</Button></section>
    </>}
    {section==="Risks"&&<>{filterBar("risk")}<div className="risk-list">{priorities.filter(r=>matches(scan.graph!.nodes.find(n=>n.id===r.nodeId)!)).map(r=>{const n=scan.graph!.nodes.find(n=>n.id===r.nodeId)!;return <article key={r.nodeId}><div className="risk-row"><strong className={"risk-score "+r.level}>{r.score}<small>/100</small></strong><div><h2>{n.name} <small>{n.version}</small></h2><p>{describeDepth(n)} · {n.scope} · {r.services.length} applications · {r.advisories} advisory IDs</p></div><Button onClick={()=>{setSelected(r.nodeId);}}>Inspect priority</Button><Button onClick={()=>select(r.nodeId,"Ripple Graph")}>Trace Ripple</Button></div>{selected===r.nodeId&&<div className="risk-breakdown"><p>{r.reasons?.join(" · ")}</p><Chart title="Why this priority?" subtitle="Deterministic triage score, not a probability of compromise." rows={Object.entries(r.factors).map(([label,count])=>({label,count}))}/><Button onClick={()=>nav("Vulnerabilities")}>Inspect vulnerabilities</Button></div>}</article>;})}{!priorities.filter(r=>matches(scan.graph!.nodes.find(n=>n.id===r.nodeId)!)).length&&<Empty text="No matching known vulnerable dependencies. Check Coverage for unchecked or unresolved packages."/>}</div></>}
    {section==="Applications"&&<><div className="application-list">{facts.applications.filter(a=>!application||a.root.id===application).map(a=>{const p=scan.repositoryMap?.projects.find(p=>p.id===a.root.projectId||"service-"+p.id===a.root.id||p.id===a.root.id);return <article key={a.root.id}><div><h2>{a.root.name}</h2><code>{p?.path||a.root.path}</code><p>{p?.ingestionStatus||p?.resolution||"Demo snapshot"}</p></div><dl><div><dt>Dependencies</dt><dd>{a.nodes.length}</dd></div><div><dt>Advisory IDs</dt><dd>{new Set(a.findings.map(f=>f.advisory.id)).size}</dd></div><div><dt>High priority</dt><dd>{a.priorities.length}</dd></div><div><dt>Runtime with findings</dt><dd>{a.nodes.filter(n=>n.scope==="runtime"&&n.advisories.length).length}</dd></div></dl><div className="application-actions"><Button onClick={()=>{setApplication(a.root.id);nav("Dependencies");}}>Dependencies</Button><Button onClick={()=>{setApplication(a.root.id);nav("Vulnerabilities");}}>Vulnerabilities</Button><Button onClick={()=>{setApplication(a.root.id);nav("Coverage");}}>Coverage</Button></div></article>;})}</div></>}
    {section==="Dependencies"&&<>{filterBar("inventory")}<div className="workspace-table-scroll"><table><thead><tr><th>Package / version</th><th>Relationship</th><th>Usage</th><th>Applications</th><th>Findings / coverage</th><th>Investigate</th></tr></thead><tbody>{scopedPackages.filter(matches).map(n=><tr key={n.id}><td><strong>{n.name}</strong><small>{versionLabel(n)} · {n.ecosystem}</small></td><td>{describeDepth(n)}</td><td>{n.scope}</td><td>{appNames(facts.appsFor(n))||"Unknown"}</td><td>{n.versionStatus==="unresolved"?"Not checked":n.advisories.length+" finding(s)"}<small>{n.versionStatus==="unresolved"?"Exact installed version unavailable":n.coverage}</small></td><td><Button onClick={()=>select(n.id,"Ripple Graph")}>Open path</Button></td></tr>)}</tbody></table></div>{!scopedPackages.filter(matches).length&&<Empty text="No dependencies match these filters."/>}</>}
    {section==="Vulnerabilities"&&<>{filterBar("vulnerability")}<p className="section-count">{scopedFindings.length} package–advisory findings · {uniqueAdvisories.size} distinct advisory IDs</p>{brief&&renderBrief(brief)}<div className="vulnerability-list">{scopedFindings.filter(f=>(f.advisory.id+" "+f.node.name+" "+f.advisory.aliases.join(" ")).toLowerCase().includes(query.toLowerCase())&&(filter==="all"||filter===severity(f.advisory)||filter==="exploited"&&f.advisory.exploited||filter===f.node.scope||filter==="indirect"&&(f.node.depth||0)>1)).map(f=><article key={f.key}><div className="vulnerability-row"><span className={"severity-dot "+severity(f.advisory)}/><div><h2>{f.advisory.id}</h2><p>{f.node.name}@{f.node.version}</p></div><span className={"severity-label "+severity(f.advisory)}>{severity(f.advisory)} · {f.advisory.cvss??"CVSS unknown"}</span><Button aria-label={"Information about "+f.advisory.id+" in "+f.node.name} onClick={()=>openBrief(f)}><Info size={19}/></Button></div><p>{f.advisory.summary}</p><footer><span>{f.applications.length} applications · {describeDepth(f.node)}</span><span>{f.advisory.exploited?"Known exploitation reported":"No exploitation evidence supplied"}</span><span>Fix: {f.advisory.fixed||"Not supplied"}</span></footer></article>)}</div>{!scopedFindings.length&&<Empty text="No known vulnerabilities were found in packages successfully checked. Review Coverage for unresolved or incomplete checks."/>}</>}
    {section==="Ripple Graph"&&<><div className="graph-selection"><label>Dependency<select aria-label="Graph dependency" value={selected} onChange={e=>setSelected(e.target.value)}>{scopedPackages.map(n=><option value={n.id} key={n.id}>{n.name}@{n.version||"unresolved"}</option>)}</select></label><Button className="primary" disabled={!paths} onClick={()=>setRipple(true)}>{node?.advisories.length?"Trace Ripple":"Trace what-if impact"}</Button>{ripple&&<Button onClick={()=>setRipple(false)}>Clear trace</Button>}</div>{paths&&ripple&&<div className="ripple-impact"><Radio/><div><h2>{paths.hypothetical?"Hypothetical impact":"Ripple traced"}: affects {paths.services.length} of {paths.totalServices} applications</h2><p>{paths.pathsTruncated?"At least ":""}{paths.pathCount} dependency paths · {paths.affected.length} dependent nodes</p><small>{paths.relationshipUncertain?"Some links are listed declarations; exact installed ancestry is uncertain. ":""}Dependency relationships do not prove vulnerable code executes.</small></div></div>}<div className="workspace-graph-layout"><DependencyGraph graph={scan.graph!} risks={scan.risks||[]} selected={selected} paths={paths} simulation={ripple?paths:null} onSelect={setSelected}/>{node&&<PackageDetails node={node} risk={risk} graph={scan.graph!} paths={paths} onTrace={()=>setRipple(true)} busy={!paths}/>}</div>{paths&&<section className="all-paths"><h2>Why is this here?</h2>{paths.paths.filter(p=>!application||p[0]===application).slice(0,15).map((p,i)=><p key={i}>{p.map((id,j)=><span key={id}>{j>0&&<ArrowRight size={13}/>}<button onClick={()=>setSelected(id)}>{scan.graph!.nodes.find(n=>n.id===id)?.name}</button></span>)}</p>)}<small>{paths.pathsTruncated?"Path enumeration was bounded; the total shown is a lower bound.":"Recorded dependency paths, not code execution reachability."}</small></section>}</>}
    {section==="Coverage"&&<><div className="coverage-summary"><h2>{checked} of {exact.length} exact versions checked</h2><p>{scopedPackages.length} dependencies discovered · {unresolved} unresolved. Unknown coverage is not safety.</p>{unresolved>0&&<p>Dependencies with no exact installed version remain in the inventory and are excluded from vulnerability matching.</p>}</div><div className="coverage-projects">{scan.repositoryMap?.projects.filter(p=>p.selected&&(!application||"service-"+p.id===application||p.id===application)).map(p=><article key={p.id}><h2>{p.name}</h2><p><code>{p.path}</code> · {p.ingestionStatus||p.resolution}</p><dl><div><dt>Detected</dt><dd>{p.packageCount??"Demo"}</dd></div><div><dt>Exact</dt><dd>{p.exactCount??"Demo"}</dd></div><div><dt>Unresolved</dt><dd>{p.unresolvedCount??0}</dd></div></dl>{p.notes.map((note,i)=><p key={i}>{note}</p>)}</article>)}</div><section className="source-health"><h2>Source availability</h2>{scan.connectors.map(c=><p key={c.name}><strong>{c.name}</strong><span>{c.status} · {c.message}</span></p>)}</section><details className="coverage-warnings"><summary>All coverage warnings ({scan.graph!.warnings.length})</summary>{scan.graph!.warnings.map((w,i)=><p key={i}>{w}</p>)}</details></>}
    {section==="Evidence"&&<><p className="section-count">Source-backed facts for {scopedFindings.length} package–advisory findings.</p><div className="evidence-list">{scopedFindings.filter(f=>!focus||f.node.id===focus.nodeId&&f.advisory.id===focus.advisoryId).map(f=><article key={f.key}><header><div><h2>{f.advisory.id}</h2><p>{f.node.name}@{f.node.version}</p></div><Button onClick={()=>{nav("Vulnerabilities");openBrief(f);}}>Open vulnerability</Button></header><dl className="fact-grid"><div><dt>Source severity</dt><dd>{severity(f.advisory)} · CVSS {f.advisory.cvss??"not available"}</dd></div><div><dt>Exploitation</dt><dd>{f.advisory.exploited?"Source-reported":"No evidence available"}</dd></div><div><dt>Fixed version</dt><dd>{f.advisory.fixed||"No verified fixed version"}</dd></div><div><dt>Aliases</dt><dd>{f.advisory.aliases.join(", ")||"None supplied"}</dd></div></dl>{f.advisory.affected?.map((a,i)=><p key={i}>{a}</p>)}<div className="evidence-links">{f.advisory.provenance.map((p,i)=><span key={i}>{p.url.startsWith("https://")?<a href={p.url} target="_blank" rel="noreferrer">{p.source}<ExternalLink size={12}/></a>:p.source}<small>Retrieved {new Date(p.retrievedAt).toLocaleString()}</small></span>)}</div></article>)}</div>{!scopedFindings.length&&<Empty text="No advisory evidence was returned in this snapshot. Source availability is recorded under Coverage."/>}<Button onClick={onExport}>Export SBOM</Button></>}
   </main>
  </div>
  {otter&&<OtterDrawer scan={scan} section={section} applicationId={application||undefined} nodeId={["Dependencies","Risks","Ripple Graph"].includes(section)?selected:undefined} focus={focus} onClearFocus={()=>setFocus(null)} onClose={()=>setOtter(false)} onNavigate={follow} api={api}/>}
 </div>;
}
function Chart({title,subtitle,rows,onClick}:{title:string;subtitle:string;rows:{label:string;count:number}[];onClick?:()=>void}){
 const max=Math.max(1,...rows.map(r=>r.count));
 return <section className="data-chart"><h2>{title}</h2><p>{subtitle}</p><div className="chart-rows">{rows.map(r=><div key={r.label}><span title={r.label}>{r.label}</span><div className="chart-track"><span className={r.label.toLowerCase().replaceAll(" ","-")} style={{width:(r.count/max*100)+"%"}}/></div><strong>{Number.isInteger(r.count)?r.count:r.count.toFixed(1)}</strong></div>)}</div>{onClick&&<button className="chart-link" onClick={onClick}>Investigate <ArrowRight size={13}/></button>}</section>;
}
function Empty({text}:{text:string}){return <div className="workspace-empty"><ScanSearch size={25}/><p>{text}</p></div>;}
